# Generated by Django 3.1.7 on 2021-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
