# Generated by Django 3.1.7 on 2021-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_player_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dinocoins',
            field=models.PositiveSmallIntegerField(default=5000),
        ),
    ]
