# Generated by Django 3.1.7 on 2021-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210323_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('life', models.PositiveSmallIntegerField(default=0)),
                ('card_type', models.CharField(choices=[('ca', 'Carnivorous'), ('he', 'Herbivore'), ('aq', 'Aquatic'), ('fl', 'Flying'), ('ev', 'Event')], default='ca', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='dinocoins',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
