# Generated by Django 3.1.7 on 2021-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210323_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack_sound',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='effect_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='img_src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('co', 'Common'), ('sc', 'Scarce'), ('ex', 'Exceptional')], default='co', max_length=2),
        ),
        migrations.AddField(
            model_name='card',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('me', 'Medium'), ('la', 'Large')], default='sm', max_length=2),
        ),
    ]
