# Generated by Django 3.1.7 on 2021-03-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_card_condition_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='attack_sound',
            new_name='intro_sound',
        ),
    ]
