# Generated by Django 3.1.7 on 2021-03-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='collection',
            name='on_deck',
            field=models.BooleanField(default=False),
        ),
    ]
