# Generated by Django 3.1.7 on 2021-03-26 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210325_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='collection',
            name='on_deck',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2, 'Maximum 2 per deck')]),
        ),
    ]
