# Generated by Django 3.1.7 on 2021-03-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210325_2235'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('Owner', 'Card_collected'), name='individual_card'),
        ),
    ]
