# Generated by Django 3.1.7 on 2021-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_deck'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('card_in_deck',), name='card(s) already in deck'),
        ),
    ]
