# Generated by Django 3.1.7 on 2021-03-29 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210329_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='on_deck',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2, 'Maximum 2 per deck')]),
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
