# Generated by Django 3.1.7 on 2021-03-29 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210329_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('Owner',)},
        ),
        migrations.AlterField(
            model_name='collection',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Cannot have 0 cards on db')]),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(check=models.Q(on_deck__lte=django.db.models.expressions.F('quantity')), name='lessEqual_than_quantity'),
        ),
    ]
