# Generated by Django 3.1.7 on 2021-03-31 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210329_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
