# Generated by Django 3.1.7 on 2021-04-17 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210331_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2, 'Maximum 2 energy cost')]),
        ),
    ]
