# Generated by Django 3.1.7 on 2021-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_card_effect_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='weak',
            field=models.CharField(choices=[('ca', 'Carnivorous'), ('he', 'Herbivore'), ('aq', 'Aquatic'), ('fl', 'Flying'), ('ev', 'Event')], default='ca', max_length=2),
        ),
    ]
