# Generated by Django 3.1.7 on 2021-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_card_weak'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='event_effect',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='card',
            name='condition_text',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
