# Generated by Django 3.1.7 on 2021-05-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20210504_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='condition_text',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
