# Generated by Django 3.1.7 on 2021-05-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210504_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='level',
            new_name='xp',
        ),
    ]
