# Generated by Django 3.1.7 on 2021-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20210511_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
