# Generated by Django 3.1.7 on 2021-05-23 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210515_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to=settings.AUTH_USER_MODEL)),
                ('Recipient_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_asked', to='backend.card')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('Sender_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_sent', to='backend.card')),
            ],
            options={
                'ordering': ('Sender',),
            },
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('Sender', 'Recipient', 'Sender_card', 'Recipient_card'), name='individual_request'),
        ),
    ]
