# Generated by Django 3.1.7 on 2021-05-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20210523_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
