# Generated by Django 3.1.7 on 2021-05-24 16:08

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20210523_1821'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(check=models.Q(Sender=django.db.models.expressions.F('Recipient'), _negated=True), name='cannot_request_themselves'),
        ),
    ]
