# Generated by Django 3.1.7 on 2021-05-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20210524_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='Recipient_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_asked', to='backend.card'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='Sender_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_offered', to='backend.card'),
        ),
    ]
