# Generated by Django 3.1.7 on 2021-05-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20210524_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Card_collected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_collection', to='backend.card'),
        ),
    ]
