# Generated by Django 3.1.7 on 2021-06-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20210526_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('Owner', 'Card_collected')},
        ),
    ]
